### ISSUE TITLE
Missing Documentation

### ISSUE THREAD

**Issue by phranck** [bjtj/swift-upnp-tools#1]
I was looking for an UPnP Swift Implementation and came over this package. Unfortunately it is missing an API documentation and example code on how to use it.

I would highly appreciate it if you can add it. 😃

**Comment by bjtj** [comment]
Thank you for your interest in my project.
Maybe it is not enough to your request, but I want you to check the following link please (swift upnp app using this project)
* https://github.com/bjtj/swift-upnp-app
And I am recently too busy with my job, but I will try to schedule to write some docs and sample codes.

**Comment by bjtj** [comment]
Check it please
- https://github.com/bjtj/swift-upnp-tools/wiki
- https://github.com/bjtj/swift-upnp-tools/blob/master/README.md

**Comment by phranck** [comment]
Well... it's just a list of classes and their method signatures. Still no documentation though. However, thank you anyway. 😃
