### ISSUE TITLE
Eventing does not work anymore after a suspend/resume cycle

### ISSUE THREAD

**Issue by meisbedi** [bjtj/swift-upnp-tools#10]
For several days I was trying to figure out, what was going on. After a suspend/resume cycle the renderer did not send no more events, although the subscription was confirmed with a OK response. I could verify, that the device, that was supposed to send events, did not send them anymore. I compared the network traffic with a known working implementation, and I could not find any reason for the behaviour of the device. Trying to mirror the way, my old app behaves (using UpnAtom and GCD Webserver) finally led me in the right direction.

swift-upnp-tools deallocates the http server as part of the suspend activities. During the resume activities, a complete new http server is created. With this configuration, I loose eventing after a suspend/resume cycle.

When I only stop the http server in the suspend function, and I don't deallocate it afterwards, the eventing is working again after a unsubscribe/ subscribe cycle as part of the resume function.

Here is the UpnpControlPoint code, I have been using:

    public func resume() throws {

        if !_suspended || !_running {
            // already suspended or not running
            return
        }

        lockQueue.sync {
            removeExpiredSubscriber()
            removeExpiredDevices()
        }
        
        _suspended = false
        
        guard let server = self.httpServer else {
            startHttpServer { (httpServer, error) in self.resumeSubscriptions() }
            return
        }
        DispatchQueue.global(qos: .default).async {
            do { try server.run { (httpServer, error) in self.resumeSubscriptions() }
            } catch let error {
                print("UPnPControlPoint: run HttpServer error - error - \(error)")
            }
        }
        startSsdpReceiver()
        try startTimer()
    }

    public func startHttpServer(readyHandler: ((HttpServer, Error?) -> Void)? = nil) {

        guard httpServer == nil else {
            print("UPnPControlPoint::startHttpServer() already started")
            guard let handler = readyHandler else { return }
            handler(self.httpServer!, nil)
            do { try self.httpServer!.run(readyHandler: readyHandler)
            } catch let error {
                print("UPnPControlPoint::startHttpServer() error - error - \(error)")
            }
            // already started
            return
        }
        
        DispatchQueue.global(qos: .default).async {

            do {
                let httpServer = HttpServer(hostname: self.hostname, port: self.port)
                self.httpServer = httpServer

                httpServer.monitor(monitorName: "cp-httpserver-monitor") {
                    (name, status, error) in
                    switch status {
                    case .started:
                        self.handleComponentStatus(.httpserver, .started)
                    default:
                        self.handleComponentStatus(.httpserver, .stopped)
                    }
                }

                try httpServer.route(pattern: "/**", handler: self)
                try httpServer.run(readyHandler: readyHandler)
            } catch let error {
                print("UPnPControlPoint::startHttpServer() error - error - \(error)")
            }// no more deallocation of self.httpServer, when httpServer.run exits
        }
    }
    
    func resumeSubscriptions() {
        self.eventSubscribers.forEach {
            $0.unsubscribe {
                (subscriber, error) in
                    guard subscriber != nil, error == nil else {
                        print("UPnPControlPoint: unsubscribe error - error - \(error!)")
                        return
                    }
                    NSLog("unsubscribed from \(subscriber?.url.absoluteString ?? "no subscriber")")
                    subscriber!.subscribe {
                        (subscriber, error) in
                            guard error == nil else {
                                print("UPnPControlPoint: subscribe error - error - \(error!)")
                                return
                            }
                            NSLog("subscribed to \(subscriber?.url.absoluteString ?? "no subscriber")")
                    }
            }
        }
    }

Please consider these findings.

**Comment by meisbedi** [comment]
Unfortunately the problem is not completely fixed with the changes I made. This morning I experienced the problem again.
I think, the issue is the way, opened sockets are handled during the finish() function of the http server.
Whenever the app is started, I don't see the problem. The problem only occurs during the suspend/resume cycle. The fact, that the app cannot recover anymore, once the problem has occurred for the first time is an indication, that the server and the socket(s) are in a status, that prevents a successful completion of the subscription. I will investigate further in that direction.
I can also confirm that the problem is not connected to a specific device. I can replicate the issue with all devices.

**Comment by meisbedi** [comment]
Finally I was able to see the issue during testing. It is not related to open/dangling sockets. When the problem occurs, the subscriptions are not renewed anymore during the resume cycle. The http server is running and receiving the event messages, because I don't unsubscribe during the suspend operation. But it looks like the subscription array was cleared during the resume cycle (handling of expired devices?). Now that I know, that I can replicate the behaviour, I have introduced debug messages in order to figure out, where the problem occurs.

With all the deep dive into the interaction between the control point and the http server during the suspend and resume cycle, I think there is still a potential issue with dangling sockets, when the listening socket gets closed while a message is handled. I would propose to use a dispatchGroup that would ensure, that the listenSocket is only closed when ongoing connection handling is completed.

**Comment by meisbedi** [comment]
I’m reopening the issue, because I cannot figure out what is going on.
During my testing I recognized, that the control points list of event subscriptions is unexpectedly empty when my app is resumed after an extended suspension time of the app (ca. 20 minutes).
Originally I was suspecting, that this was caused by the removal of devices due to a timeout, that is running at the beginning of the resume function. Therefore I added log messages to trace such activities. But the problem reoccurred and there was no indication, that a device was removed (and the associated event subscriptions unsubscribed) by a timeout. To be sure, I removed the device and subscription timeout check completely from the resume function. But I still have the problem, that the event subscriptions are gone after the suspend/resume cycle.
Somebody is pulling the rug from underneath my feet, and I have no idea, who that might be, because I have monitored all the functions, that access the array of subscriptions, and none of them is executed. It is also strange, that it happens only after extended down times of the app (still the downtime is below the timeout;  I checked the remaining time of all devices during the resume function).

Any help to solve this mystery is highly appreciated.

**Comment by bjtj** [comment]
I see, I will check it too. Can you tell me what upnp device is used for the test, so that I can reproduce the issue in my side?
Thank you ;)

**Comment by meisbedi** [comment]
I’m testing with an iPad as well as with an iPhone. The problem exists with both devices. I will still need to be patient enough to see if the problem also occurs with the simulator of the XCode development suite.

**Comment by meisbedi** [comment]
I think, I found the problem. I did set a watchpoint on the eventSubscribers variable in the debugger and then I recognised, that in the timer routine, that monitors the timeout for devices and subscribers, the subscriber array is bluntly filtered without any further actions:


    func removeExpiredSubscriber() {
        // TODO: on event subscription removed
        eventSubscribers.removeExpired(handler: subscription(removed:))
    }

I was focused on the device timeouts in my investigation, where the proper actions for handling the timeout are already implemented. Therefore I also forgot to handle subscription timeouts, because I was under the misguided impression, that the current implementation just ignores the subscription timeouts, while it is actually pulling the rag, without letting anybody up the chain know, what is about to happen. Shame on me, to not fully understand, what is behind your remark "TODO: on event subscription removed", which hints on exactly the deficit, I was running into.

As a temporary fix, I'm currently resetting the timeouts of all devices and subscriptions at the beginning of the resume function. To be honest, on my own "to do" list, I have a remark to investigate the correct way of actively handling the network situation after the app was suspended and resumed. I would propose, that the control point only sends an information, that the timeout of devices and subscriptions expired during the app suspension. Then it would be up to the app to update the current configuration of the devices and subscriptions. Should the device time out again after resuming, then it is obvious the right thing to remove it (and the associated subscriptions) by the control point.

**Comment by meisbedi** [comment]
I think I have it figured out. Now the device with the event, to which I subscribed complains about the "unsubscribe" command that I send during the resume function with an HTTP error code of 412:

Error code for the "UNSUBSCRIBE" command from the official UPnP description for devices under the eventing paragraph:
Invalid SID
412 Precondition Failed. If a SID does not correspond to a known, un-expired subscription, the publisher must respond with HTTP error 412 Precondition Failed.

Now I just catch this conditions and hopefully everything will work as intended. More to come ;-)

**Comment by meisbedi** [comment]
For the first time, I did see, that the subscriptions are kept after the long suspended status of the app. I think, this is it.
