### ISSUE TITLE
How to create a renderer?

### ISSUE THREAD

**Issue by geofstro** [bjtj/swift-upnp-tools#11]
I want my app to be able to act as a upnp renderer. Can I do this with swift-upnp-tools?

If not are there any plans to add this in the future. The examples show a Control Point and a Server; but no Renderer.

Apologies, as this isn't really an issue; perhaps more a feature request?

**Comment by meisbedi** [comment]
The server contains the necessary elements to create a renderer:
- announcing a device
- Replying to the request for device and service descriptions 
- Replying to SOAP requests
- Sending event messages for status changes

You will need to provide the device and service descriptions as well as the functions that handle the SOAP requests and trigger events and actually stream content.

**Comment by geofstro** [comment]
Thanks very much for your advice. Do you think you can provide a simple example of implementing a renderer? I'm new to upnp. Thanks again.

**Comment by meisbedi** [comment]
Unfortunately I don’t have any sample code for a renderer. I have used this package to build a control point.
I had a quick look at the server sample code from the readme file and it looks like bjtj took already care of most of the basics. I can offer to do some reverse engineering and give you some input on how to leverage the package to build a renderer.

**Comment by geofstro** [comment]
I would really appreciate that, thanks.

**Comment by meisbedi** [comment]
Ok. But it will take a little while. I will be busy with other things the next couple of days.

**Comment by geofstro** [comment]
Of course, I understand, when you have the time. I really appreciate it!

**Comment by meisbedi** [comment]
Hi there,

I found some time to look a little deeper into the function of the UPnP server. I can confirm, that in general all the heavy lifting will be covered by the package. But it looks to me, that it will require some debugging.

So let's go step by step.
First you need a xml file, that contains a device description.
[xml device description.txt](https://github.com/bjtj/swift-upnp-tools/files/10267083/xml.device.description.txt)
I have attached a standard description from the UPnP standard.
For each service, that the renderer supports, you need a service description.
[xml connection manager service description.txt](https://github.com/bjtj/swift-upnp-tools/files/10267129/xml.connection.manager.service.description.txt)
[xml transport1 service description.txt](https://github.com/bjtj/swift-upnp-tools/files/10267131/xml.transport1.service.description.txt)
[xml renderingControl service description.txt](https://github.com/bjtj/swift-upnp-tools/files/10267127/xml.renderingControl.service.description.txt)
I have attached template of the standard descriptions.
I have also attached the descriptions from the UPnP standard.
[UPnP-av-MediaRenderer-v3-Device-20130331.pdf](https://github.com/bjtj/swift-upnp-tools/files/10267146/UPnP-av-MediaRenderer-v3-Device-20130331.pdf)
[UPnP-av-ConnectionManager-v3-Service-20130331.pdf](https://github.com/bjtj/swift-upnp-tools/files/10267148/UPnP-av-ConnectionManager-v3-Service-20130331.pdf)
[UPnP-av-AVTransport-v3-Service-20130331.pdf](https://github.com/bjtj/swift-upnp-tools/files/10267150/UPnP-av-AVTransport-v3-Service-20130331.pdf)
[UPnP-av-RenderingControl-v3-Service-20130331.pdf](https://github.com/bjtj/swift-upnp-tools/files/10267154/UPnP-av-RenderingControl-v3-Service-20130331.pdf)
These documents describe the contents of the xml files.

Now the first steps to setup a renderer.
With the package you create a device based on the device description xml and the service xml. This is accomplished by calling the "read" function of the UnPDevice class with the content of the device description xml file and thus creating a UpnPDevice instance.

The you create the service by calling the "read" function of the UPnPService class with the content of the service description xml file. You add the resulting UPnPService instance to the services array of the UPnPDevice instance.

You register the device instance with the upnp server.

You tell the upnp server to announce the device.

The server handles all the communication that happens, when a control point detects the device (your renderer) and ask for the device and service descriptions.

Your software will need to take care of handling all the SOAP action requests, that are received from the control point and you will need to take care of the event messaging.
The Upnp server has these functions for this:
 - actionRequestHandler for SOAP action requests
 - sendEventProperties for event messaging
 
Please let me know, when you have specific questions.

**Comment by geofstro** [comment]
Hi,
That's extremely useful. Thanks so much for going to the trouble of putting this together. I will make a start based on this, then, yes, probably will have some questions along the way.

**Comment by geofstro** [comment]
Hi Meisbedi,

I have only just had the time this week to make a start on this following the holiday season.

I hope the New Year has got off to a good start for you?

So, here is where I've got to…

"With the package you create a device based on the device description xml and the service xml. This is accomplished by calling the "read" function of the UnPDevice class with the content of the device description xml file and thus creating a UpnPDevice instance."

Done!

"Then you create the service by calling the "read" function of the UPnPService class with the content of the service description xml file. You add the resulting UPnPService instance to the services array of the UPnPDevice instance."

Done for all three services;

connection manager service
transport service
rendering control service

"You register the device instance with the upnp server.
 
Done!

You tell the upnp server to announce the device."

Done!

In a previous message you pointed out that… "The server contains the necessary elements to create a renderer:"

It took me a while to get my head around the fact that, although I only want to create a Media Renderer that will be seen from external control points/servers on the LAN, I will need a server to handle soap requests; etc.

The server example in this package is for a "Dimmable Light"; but the appropriate server on this case would need to be a "Media Server", right?

So I went looking for a device description xml template for a Media Server.

I found one and tried to base my Media Server on that.

This requires the three services, AVTransport:1, ConnectionManager:1 and ContentsFolder:1

The first two I already have defined and added to my Media Renderer; but I don't have an scp template for the ContentsFolder service.

So I went looking for one and found one.

When I go through the registration process for my Media Server and try to add these services on the way, it fails though.

It doesn't seem to be able to add any of these services during the registration process and so fails.

I don't know if the fault lies with my device description template or any of the services templates.

The (slightly) encouraging part is that the Media Renderer tries to show up on the network for the first time, when I try starting my Media Server; but it shows with the indication "Operation Failed with:
custom(string: "no device") as the XML description file.

I don't know if the "no device" refers to the server or the renderer. If I don't try to register my Media Server though, my device doesn't even try to show up on the network.

Any further advice will be much appreciated.

**Comment by meisbedi** [comment]
Hi geofstro,

I'm happy to hear that your project start was successful.

Looking at your description, I think you got confused by the term "server" that is used within the upnp-tools package.
You will not need a UPnP Media Server for your purpose.
The server, that is part of the upnp-tools package, should be considered a server for your application. It provides you with the necessary tools to interact with a control point on the UPnP network.

There is a contradiction in your feedback.
You write: "You tell the upnp server to announce the device. Done!"
And: "If I don't try to register my Media Server though, my device doesn't even try to show up on the network."

I suspect, that the first part did not work properly. Did you use the "activate" function of the UPnP server class?
You should debug the activate function, because there are some guard statements in the "announceDeviceAlive" function chain, that return after failed checks without indication of a problem.

**Comment by geofstro** [comment]
Thanks for your rapid response and for clarifying that I should use the built in server. The contradiction comes from my confusion over this issue.

What I meant was, that I was calling the "announceDeviceAlive" and "announceDeviceUpdate" functions of the Media Server that I attempted to create. This at least showed something up on the network; but obviously it didn't work.

Can you tell me which of the functions of the built in server I need to call?

Currently I'm calling:

    server.registerDevice(device: upnpRenderer)
    server.activate(device: upnpRenderer)
    server.announceDeviceUpdate(device: upnpRenderer)
    server.announceDeviceAlive(device: upnpRenderer)

Where "upnpRenderer" is the Media Renderer I've created from the device description, and service templates and "server" is an instance of the built in UPnPServer from the package.

I've calling just "activate", "activate" and "announceDeviceAlive" and all three of the above.

None of these attempts cause my renderer to show up on the network, even in a failed state.

**Comment by meisbedi** [comment]
Actually, just the call
server.activate(device: upnpRenderer)
should make the renderer visible on the network.

It looks like this needs a little deeper digging, and it is possible, that there is an issue with the package.
I can offer you, to setup a video conference in order to try to figure out, where the problem is coming from. Are you interested?

**Comment by geofstro** [comment]
Yes, definitely …thanks. Please let me know what would be a good time for you.

BTW, this is probably a stupid question; but where does my upnpRenderer get its port from? Is it the same port as I allocate when I create my instance of UPnPServer?

**Comment by meisbedi** [comment]
That area is a possible cause for the problem.
Your assumption about the port is correct. Is is the port of the UPnPServer and it should be 52808.
I would be available for a discussion right now. I'm on a Mac, so Facetime would be my preferred platform for communication. I can be reached at: Dieter.Meisberger@gmx.de

**Comment by geofstro** [comment]
Thank for the offer, I have to pick my daughter up from school first though. If you're available around 6:30 pm, I could do it then. I'm also on Mac Facetime.

**Comment by meisbedi** [comment]
Key question is: 6:30 pm of which timezone?

**Comment by geofstro** [comment]
I’m in Monaco/France. So same as you, I believe?Sent from my iPhoneOn Jan 12, 2023, at 16:10, meisbedi ***@***.***> wrote:﻿
Key question is: 6:30 pm of which timezone?

**Comment by meisbedi** [comment]
Great. So 6:30 pm works for me. Talk to you soon.

**Comment by geofstro** [comment]
👍👍👍

**Comment by meisbedi** [comment]
Here are a couple of updated files in preparation of the meeting.
[xml device description.txt](https://github.com/bjtj/swift-upnp-tools/files/10403754/xml.device.description.txt)
[xml connection manager service description.txt](https://github.com/bjtj/swift-upnp-tools/files/10403755/xml.connection.manager.service.description.txt)
[xml transport1 service description.txt](https://github.com/bjtj/swift-upnp-tools/files/10403756/xml.transport1.service.description.txt)
[xml renderingControl service description.txt](https://github.com/bjtj/swift-upnp-tools/files/10403760/xml.renderingControl.service.description.txt)

I recognised that the previous files did not contain all necessary data.

**Comment by geofstro** [comment]
Thanks for the updated files. I've updated mine with them.

We actually got back early. So if you'd like to make the call now, I can, or we can stick to 6:30, if you prefer.

Please let me know.

**Comment by geofstro** [comment]
It is now perfectly possible to create a Media Renderer with this package following the issues opened by @meisbedi, and the subsequent fixes via the recent merged pull requests from the developer. Thank you!
