### ISSUE TITLE
SSDP messages from the UPnPServer class are missing the required "SERVER" field

### ISSUE THREAD

**Issue by meisbedi** [bjtj/swift-upnp-tools#14]
As per the UPnP specification, SSDP messages, that contains announcements from devices (ssdp:alive, ssd:byebye, ssdp:update) and the response for a SSDP Msearch message are required to contain a "SERVER" header field. This is currently missing.

SERVER
Required. Specified by UPnP vendor. String. Field value shall begin with the following “product tokens” (defined by HTTP/1.1). The first product token identifes the operating system in the form OS name/OS version, the second token represents the UPnP version and shall be UPnP/2.0, and the third token identifes the product using the form product name/product version. For example, “SERVER: unix/5.1 UPnP/2.0 MyProduct/1.0”.

To fix it, I created a static function "userAgent" within the SSDPHeader class, that creates the required string. 

    public static func userAgent() -> String {
        if let info = Bundle.main.infoDictionary {
            let executable = info[kCFBundleExecutableKey as String] as? String ?? "Unknown"
            let appVersion = info["CFBundleShortVersionString"] as? String ?? "Unknown"
            
            let osNameVersion: String = {
                let versionString: String
                
                if #available(OSX 10.10, *) {
                    let version = ProcessInfo.processInfo.operatingSystemVersion
                    versionString = "\(version.majorVersion).\(version.minorVersion).\(version.patchVersion)"
                } else {
                    versionString = "10.9"
                }
                
                let osName: String = {
                    #if os(iOS)
                        return "iOS"
                    #elseif os(watchOS)
                        return "watchOS"
                    #elseif os(tvOS)
                        return "tvOS"
                    #elseif os(OSX)
                        return "OS X"
                    #elseif os(macOS)
                        return "MacOS"
                    #elseif os(Linux)
                        return "Linux"
                    #else
                        return "Unknown"
                    #endif
                }()
                
                return "\(osName)/\(versionString)"
            }()
            return "\(osNameVersion) UPnP/1.1 \(executable)/\(appVersion)"
        }
        return "Unknown"
    }

Then I simply create the header field within the applicable functions like that:

        properties["SERVER"] = SSDPHeader.userAgent()

or for the MSearch response:

        header["SERVER"] = SSDPHeader.userAgent()

**Comment by meisbedi** [comment]
I reviewed this topic again, and the "SERVER" header field is only needed on the ssd:alive message.

**Comment by bjtj** [comment]
> I reviewed this topic again, and the "SERVER" header field is only needed on the ssd:alive message.

Thank you
