### ISSUE TITLE
UPnP server class device announcement

### ISSUE THREAD

**Issue by meisbedi** [bjtj/swift-upnp-tools#16]
I compared the current device announcement of the UPnP server class, and I recognised two small issues.

For each root device, 3 discovery messages should be send. In the current implementation, the message with the "NT" header field containing the "uuid:device-UUID" value is sent at the end of the messages with the service discovery. From. my point of view, this message should be the second message after the message with the "NT" header field value "upnp:rootdevice".

When an embedded device would be present, each embedded device should be announced with two device specific messages and one message for each service. In the current implementation, only one discovery message is send for each embedded device.
The first message should have the value "uuid:device-UUID" in the "NT" header field (this one is missing).
The second message should contain "urn:schemas-upnp-org:device:deviceType:ver" in the "NT" header field (this one is present).

I changed the loop of the embedded Devices in the allServiceType computed property of the UPnPDevice class as follows:

        for embeddedDevice in embeddedDevices {
            guard let embeddedUdn = embeddedDevice.udn else { continue }
            types.append(UPnPUsn(uuid: embeddedUdn))
            if let serviceTypes = embeddedDevice.allServiceTypes {
                types += serviceTypes
            }
        }

Additionally, according to the UPnP standard, the ssd:alive messages should be repeated on a regular basis. Your UPnPServer class sends an ssd:update message instead.

**Comment by meisbedi** [comment]
The content of the device announcement has been properly corrected.
But there is a small issue. You have introduced a loop to repeat the initial announcement. But you loop over the individual announcement categories (root, device, service, embedded device) instead over a complete announcement block.

**Comment by bjtj** [comment]
![image](https://user-images.githubusercontent.com/1907889/215604455-bd09408d-17f3-4f3d-bbdd-5e7fdbbaa550.png)

I referenced the behavior of av media server in [upnp developer tool](https://www.meshcommander.com/upnptools).
It may be make udp packet more possible to reach to other devices.
And I try to find about repeating announcement at first time of device in upnp spec document, but I cannot find a detail..
So, I decided to follow the standard tool's behavior.

**Comment by meisbedi** [comment]
I understand. This is a typical case, where interpretation of the standard comes into play. I had looked at the description of the "NOTIFY with ssd:alive" message within the UPnP-arch-DeviceArchitecture document.
<img width="773" alt="Bildschirm­foto 2023-02-01 um 12 17 05" src="https://user-images.githubusercontent.com/22547751/216029089-cfd8b082-6f3f-4f3f-93eb-2a9f01c00b9c.png">
There it says, that the entire set of discovery messages should be sent more than once. This lead to my conclusion, that the repeat loop should go over the announcement block.
In general, the current implementation meets the requirement of sending the messages more than once, but the requirement of a few hundred milliseconds in not fulfilled, because the announcements follow each other in very short distances.

**Comment by meisbedi** [comment]
This should do the trick. Thank you
