### ISSUE TITLE
Is there an example of using UPnPServer?

### ISSUE THREAD

**Issue by YJZhen** [bjtj/swift-upnp-tools#2]
Is there an example of using UPnPServer? I hope my Mac can be scanned by the mobile device

**Comment by bjtj** [comment]
If you check the test code, there're some snippet of code to start upnp server.

https://github.com/bjtj/swift-upnp-tools/blob/e85aebdad191f81e4fc46ff8d494f708fc054c7f/Tests/swift-upnp-toolsTests/swift_upnp_toolsTests.swift

https://github.com/bjtj/swift-upnp-tools/blob/e85aebdad191f81e4fc46ff8d494f708fc054c7f/Tests/swift-upnp-toolsTests/swift_upnp_toolsTests.swift#L7

https://github.com/bjtj/swift-upnp-tools/blob/e85aebdad191f81e4fc46ff8d494f708fc054c7f/Tests/swift-upnp-toolsTests/swift_upnp_toolsTests.swift#L249-L253

https://github.com/bjtj/swift-upnp-tools/blob/e85aebdad191f81e4fc46ff8d494f708fc054c7f/Tests/swift-upnp-toolsTests/swift_upnp_toolsTests.swift#L178-L194
