### ISSUE TITLE
UPnPServer class "onBodyCompleted" method adds unnecessary "SERVER" response field

### ISSUE THREAD

**Issue by meisbedi** [bjtj/swift-upnp-tools#29]
At the very beginning of the "onBodyCompleted" method a "SERVER" key is added to the HttpResponse properties.
This key is only valid for SSDP alive messages. The proper key for HttpResponses is "User-Agent". but it has a different content from the "SERVER" key for SSDP messages.

**Comment by bjtj** [comment]
I list up the cases of occuring user-agent and server field from upnp spec.

*USER AGENT*

- msearch request
- action soap request
- subscribe request

*SERVER*

- notify:alive
- msearch response
- action response
- action error response
- subscribe response

I will fix it as above.

Thanks.

**Comment by meisbedi** [comment]
👍
