### ISSUE TITLE
error - Error code: -9992(0x-2708), Operation not permitted

### ISSUE THREAD

**Issue by simon-lucas** [bjtj/swift-upnp-tools#3]
I am running this with xcode12.4. Swift 4.2 on MacOS 10.15.7. Compiling for desktop MacOS.

Going through the sample Control Point code lien by line, I got this error

error - Error code: -9992(0x-2708), Operation not permitted

As soon as I add the line cp.run()

            let cp = UPnPControlPoint(port: 1900)
            cp.onDeviceAdded {
                (device) in
                DispatchQueue.global(qos: .background).async {
                
                }
            }
            
            cp.run()

            cp.finish()

**Comment by bjtj** [comment]
Please try to set the port number to 0 (any port to bind).

```
let cp = UPnPControlPoint(port: 1900)
```

**Comment by simon-lucas** [comment]
Thank-you. Yes. I tried 'port: 0' at the first time. It was the same error. I later tried port:1900 as I read that it was the standard UPnP port number. It makes no difference to the error.

**Comment by bjtj** [comment]
Actually, the port number is http server bind port. (It seems I have to change the name to prevent confusing)

I have a problem with reproducing the issue because I have no macos device.

I will try to reproduce the issue with my best but I cannot sure when it will possible.

**Comment by simon-lucas** [comment]
bjtj. Your comment about MacOS made me think to just get this running on iOS. And now the problem has gone away. 

So, I am going through your example code and have made some ammendments where it comes to dealing with the devices as Dictionary entries. All that works now, but I have one problem and that is an unknown type: Session - that is not in any of the dependencies. Could you tell me what library that type comes from ,please? 

Thank-you

**Comment by simon-lucas** [comment]
I'm having trouble with this line in your example code

cp.invoke(service: service, action: action, properties: properties)

because action is the wrong type, as is properties. Also I'm not clear how to pass the UPnPSoapResponse handler in. I think your example was written for an earlier version of the library, perhaps?

//properties
OrderedProperties the class is inaccesible due to internal protection error. Redefining it in my scope causes a non-matching type error. I have set properties to be OrderedProperties type.

//action
action is defined as UPnPAction, not a string. I am trying action.name here.

I'm running up against errors that are beyond my level of Swift coding.

Is there any chance of an updated example please?

**Comment by simon-lucas** [comment]
My fix included 

i. Change var properties to type OrderedProperties:

var properties = OrderedProperties()

ii. In container.swift add init to the OrderedProperties class 

add

public init() {
                
}

iii. Using action.name! to access the action as a string , in 
cp.invoke(service: service, action: action.name!, properties: properties)

After this it compile and worked. I recieved a list of servers on the network.


Full changes below:

-----------

//
//  ViewController.swift
//  UpNUpTooliOS
//
//  Created by Simon Lucas on 13/11/2021.
//

import UIKit
import SwiftUpnpTools

class ViewController: UIViewController {
    var device: UPnPDevice?
    struct Session {
        var device: UPnPDevice?
        var service: UPnPService?
    }
    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view.
        var session = Session()
        print("p")
        var done = false
        let cp = UPnPControlPoint(port: 0)
        cp.run()
        cp.onDeviceAdded {
                (device) in
                print("device added -- \((device as UPnPDevice).udn ?? "nil") / \(((device as UPnPDevice)).friendlyName ?? "nil")")
        }
        cp.onDeviceRemoved {
                (device) in
                print("device removed -- \(device.udn ?? "nil") / \(device.friendlyName ?? "nil")")
        }
        cp.onEventProperty {
                (sid, properties) in
                print("event notify -- sid: \(sid)")
                for field in properties.fields {
                    print("- \(field.key): \(field.value )")
                }
            }
        while done == false {
                guard let line = readLine() else {
                    continue
                }
                let tokens = line.split(separator: " ", maxSplits: 1).map { String($0) }
                guard tokens.isEmpty == false else {
                    print(" == session ==")
                    guard let device = session.device else {
                        print("device is not selected")
                        continue
                    }
                    print("device -- \(device.udn ?? "nil") \(device.friendlyName ?? "nil")")
                    for service in device.services {
                        print(" - \(service.serviceType ?? "nil")")
                    }
                    guard let service = session.service else {
                        print("service is not selected")
                        continue
                    }
                    print("service -- \(service.serviceType ?? "nil")")
                    continue
                }
                switch tokens[0] {
                case "quit", "q":
                    done = true
                    break
                case "search":
                    cp.sendMsearch(st: tokens[1], mx: 3)
                case "ls":
                    print(" == devices (count: \(cp.devices.count)) ==")
                    for (key, device) in cp.devices {
                        print("* \(device.udn ?? "nil") -- \(device.friendlyName ?? "nil")")
                    }
                case "device":
                    guard let idx = Int(tokens[1]) else {
                        print("not integer")
                        continue
                    }
                    guard idx >= 0 && idx < cp.devices.count else {
                        print("not in range")
                        continue
                    }
                    let indx = cp.devices.index(cp.devices.startIndex, offsetBy: idx)
                    let device = cp.devices[indx]
                    print("idx: \(idx) -- \(device.value.udn ?? "nil") \(device.value.friendlyName ?? "nil")")
                    for service in device.value.services {
                        print(" - service: \(service.serviceType ?? "nil")")
                    }
                    session.device = device.value
                case "service":
                    guard let device = session.device else {
                        print("device is not selected")
                        continue
                    }
                    let serviceType = tokens[1]
                    guard let service = device.getService(type: serviceType) else {
                        print("no service found -- \(serviceType)")
                        continue
                    }
                    session.service = service
                    print("selected service id -- \(service.serviceId ?? "nil")")
                    guard let scpd = service.scpd else {
                        print("no scpd")
                        continue
                    }
                    for action in scpd.actions {
                        print("- action: \(action.name ?? "nil")")
                    }
                case "invoke":
                    guard tokens.count > 1 else {
                        print("action name is required")
                        continue
                    }
                    guard let service = session.service else {
                        print("service is not selected")
                        continue
                    }
                    guard let scpd = service.scpd else {
                        print("service has no scpd")
                        continue
                    }
                    guard let action = scpd.getAction(name: tokens[1]) else {
                        print("no action name -- \(tokens[1])")
                        continue
                    }
                    var properties = OrderedProperties()
                    for argument in action.arguments {
                        guard let name = argument.name else {
                            continue
                        }
                        print("- in argument: \(name)")
                        guard let argumentValue = readLine() else {
                            print("failed to read argument value")
                            return
                        }
                        properties[name] = argumentValue
                    }
                    
                    //public func invoke(service: UPnPService, action: String, properties: OrderedProperties, completeHandler: ((UPnPSoapResponse?) -> Void)?) {
                    cp.invoke(service: service, action: action.name!, properties: properties) {
                        (soapResponse) in
                        guard let soapResponse = soapResponse else {
                            print("no soap response")
                            return
                        }
                        print("action response")
                        for field in soapResponse.fields {
                            print("- \(field.key): \(field.value)")
                        }
                    }
                case "subscribe":
                    guard let service = session.service else {
                        print("service is not selected")
                        continue
                    }
                    cp.subscribe(service: service) {
                        (subscription) in
                        print("subscribe is done -- \(subscription.sid)")
                    }
                default:
                    print("unknown command -- \(tokens[0])")
                }
            }
    }


}

**Comment by bjtj** [comment]
I have added new tag ([0.1.8](https://github.com/bjtj/swift-upnp-tools/releases/tag/0.1.8))

`OrderedProperties` is my implementation
* https://github.com/bjtj/swift-upnp-tools/wiki/OrderedProperties

You can use `OredredProperties` as a map
e.g.
```swift
var fields = OrderedProperties()
fields["LOCATION"] = "http://example.com"
```

I have added `UPnPActionRequest` class
* https://github.com/bjtj/swift-upnp-tools/blob/master/Sources/swift-upnp-tools/UPnPActionRequest.swift

https://github.com/bjtj/swift-upnp-tools/blob/0e40c6caf31d98d5cd52766ae926993c265ef590/Sources/swift-upnp-tools/UPnPActionRequest.swift#L21

And I added another `invoke()` method in [UPnPControlPoint](https://github.com/bjtj/swift-upnp-tools/blob/master/Sources/swift-upnp-tools/UPnPControlPoint.swift) which use `UPnPActionRequest`

https://github.com/bjtj/swift-upnp-tools/blob/0e40c6caf31d98d5cd52766ae926993c265ef590/Sources/swift-upnp-tools/UPnPControlPoint.swift#L351

**Comment by simon-lucas** [comment]
Thank-you for you help
Simon
