### ISSUE TITLE
UPnPStateVariable does not support the UPnP standard for eventing support

### ISSUE THREAD

**Issue by meisbedi** [bjtj/swift-upnp-tools#30]
According to the UPnP standard, the state variable format for a service description is the following:

<stateVariable sendEvents="yes">
<name>LastChange</name>
<dataType>string</dataType> 
</stateVariable>

The current UPnPStateVariable implementation does not support the sendEvents attribute of the xml tag.

Solution:

UPnPStateVariable should get an additonal property.

    public var evented = false

The read() method need to have this additional line:

        stateVariable.evented = (xmlElement.getAttribute(name: "sendEvents")?.value ?? "no") == "yes"

The computed property description needs the following adaptation:

    public var description: String {
        let tag = XmlTag(name: "stateVariable", ext: "sendEvents=\"\(self.evented ? "yes":"no")\"",content: propertyXml)
        return tag.description
    }

**Comment by bjtj** [comment]
```
<stateVariable sendEvents="yes"|"no" multicast="yes"|"no">
```

I will add `multicast` attribute also.

Thank you.
