### ISSUE TITLE
SOAP Actions are not properly formatted

### ISSUE THREAD

**Issue by meisbedi** [bjtj/swift-upnp-tools#4]
When trying to send a SOAP action to a UPnP service, I received an error code 500.
A comparison with the HTTP request, that is actually working, I recognised, that the SOAP action request ist not properly terminated with quotes.

I tested the following change on the function "soap action" in the module UPnPSoap and it fixed the problem:

    public var soapaction: String {
        return "\"\(serviceType)#\(actionName)\""
    }

**Comment by bjtj** [comment]
Thank you!

I fixed it and I found another issue on swift xml and I fixed it also.

commit: https://github.com/bjtj/swift-upnp-tools/commit/26a05c520e9384a71aea70b1781749209b09e53e

**Comment by meisbedi** [comment]
I tested the fix and it is effective. Thank you very much for the fast action.
Your package looks very nice and lean. I'm looking forward to test it in more detail.
I'm actually considering to replace UpnpAtom with your package in my project.
