### ISSUE TITLE
Service description is not retrieved due to missing baseUrl in device

### ISSUE THREAD

**Issue by meisbedi** [bjtj/swift-upnp-tools#5]
I recognised, that the service description document is not retrieved after a device is detected.
There are two problems.
The baseUrl of the device is set, after the DeviceBuilder tries to retrieve the service description.
There is  only the url of the device description xml available.

To fix this, I did two things.

I created an additional variable urlFromXml in the device.
I created a computed baseUrl property, that extracts the baseUrl from the device description Url.

I moved the setting of the url value in the device inside the DeviceBuilder.

Code:

UPnPDevice

    /**
     base url
     */
    public var urlFromXml: URL?     // new variable for device description url
    public var baseUrl: URL! { return URL(string: "/", relativeTo: urlFromXml)?.absoluteURL }  // computed baseUrl

UPnPDeviceBuilder

            guard let device = UPnPDevice.read(xmlString: xmlString) else {
                print("UPnPDevice.read() failed")
                print(xmlString)
                return
            }
            device.urlFromXml = url           // set the urlFromXml before the services are handled
            let services = device.allServices
            for service in services {
                UPnPScpdBuilder(service: service).build()
            }

UPnPControlPoint

    public func onDeviceBuild(url: URL?, device: UPnPDevice?) {
        guard let device = device, let url = url else {
            return
        }
//        device.baseUrl = url      //late setting of baseUrl can be removed
        addDevice(device: device)
    }

I tested the changes and the service descriptions are properly retrieved

**Comment by bjtj** [comment]
Thank you!

I fixed it (tag: [0.1.12](https://github.com/bjtj/swift-upnp-tools/releases/tag/0.1.12))

I simply set baseUrl before getting scpd because it seems no problem.

https://github.com/bjtj/swift-upnp-tools/blob/d78e8346b7331fa1882780f1b0b667f99346d5a2/Sources/swift-upnp-tools/UPnPDeviceBuilder.swift#L49-L61

**Comment by meisbedi** [comment]
I tested your latest version and I'm sorry to report, that this is not enough. Please see below a screenshot, that shows the url that is used in the UPnPScpdBuilder.
<img width="1383" alt="Bildschirmfoto 2021-11-20 um 11 17 47" src="https://user-images.githubusercontent.com/22547751/142722814-5295eeed-b568-4060-b6d0-6b7487f25881.png">
This url is obviously not correct. Therefore you will need to eliminate all elements form the baseUrl after the slash "/". The simplest way would be to adapt the build function in UPnPScpdBuilder , that creates the Url like that:
        guard let baseUrl = URL(string: "/", relativeTo: device.rootDevice.baseUrl)?.absoluteURL else {
            return
        }

I verified this change with your version 0.1.12 and it works. You need to keep in mind though, that the Scpd property of the service will be filled asynchronous. Therefore, these values might not be available immediately after device detection. It might be a good idea, to add a hook like "onServiceScpdDetected" to make users of the device/service aware, that the service description is available.

Thanks for your efforts

**Comment by meisbedi** [comment]
I have to apologise. I fell into the trap with the asynchronous load of the service description. I double checked the url of my change and it looked exactly like the url in the screenshot above. This is how I recognised that I got fooled by the asynchronous load. It would still be a good idea though, to somehow indicate, that loading of the service description is in progress/failed/completed.
