### ISSUE TITLE
Event subscription is not possible

### ISSUE THREAD

**Issue by meisbedi** [bjtj/swift-upnp-tools#6]
I was looking into event subscription and I recognized several issues.

There are typos in the name of the header field TIMEOUT for the subscription. Additionally, the response from the device might contain "Sid" instead of "SID" in the response header.
    /**
     Subscribe
     */
    public func subscribe(completeListener: ((UPnPEventSubscription) -> Void)? = nil) {
        var fields = [KeyValuePair]()
        fields.append(KeyValuePair(key: "NT", value: "upnp:event"))
        fields.append(KeyValuePair(key: "CALLBACK", value: callbackUrls.map{"<\($0)>"}.joined(separator: " ")))
        fields.append(KeyValuePair(key: "_TIMEOUT_", value: "Second-\(timeout)")) /**/ typo: TIEMOUT**
        HttpClient(url: url, method: "SUBSCRIBE", fields: fields) {
            (data, response, error) in

            guard error == nil else {
                print("[subscribe] error - '\(error!)'")
                return
            }
            
            guard let response = response as? HTTPURLResponse else {
                print("[subscribe] not http url response")
                return
            }
            
            guard let sid = response.allHeaderFields["_Sid_"] as? String else {  **// changed to "Sid" due to spelling in the device response**
                print("[subscribe] NO SID")
                return
            }

            var second: UInt64 = 1800
            if let timeout = response.allHeaderFields["Timeout"] as? String {
                let start = timeout.index(timeout.startIndex, offsetBy: "Second-".count)
                second = UInt64(String(timeout[start..<timeout.endIndex]))!
            }
            self.sid = sid
            let subscription = UPnPEventSubscription(service: self.service, sid: sid, timeout: second)
            completeListener?(subscription)
        }.start()
    }

    /**
     Review Subscription
     */
    public func renewSubscribe() {

        guard let sid = sid else {
            return
        }
        
        var fields = [KeyValuePair]()
        fields.append(KeyValuePair(key: "SID", value: sid))
        fields.append(KeyValuePair(key: "_TIMEOUT_", value: "Second-\(timeout)")) **// typo TIEMOUT**
        HttpClient(url: url, method: "SUBSCRIBE", fields: fields) {
            (data, response, error) in
        }.start()
    }

The HTTP server needs to take the different spelling of "SID" in the header also into account:
    public func startHttpServer() {
        
        DispatchQueue.global(qos: .default).async {

            guard self.httpServer == nil else {
                // already started
                return
            }
            do {
                self.httpServer = HttpServer(port: self.port)
                try self.httpServer!.route(pattern: "/Event") {
                    (request) in
                    guard let request = request else {
                        print("UPnPControlPoint::startHttpServer() error - no request")
                        return nil
                    }
                    print("UPnPControlPoint::startHttpServer() error - path -- \(request.path)")
                    
                    guard let contentLength = request.header.contentLength else {
                        print("UPnPControlPoint::startHttpServer() error - no content length")
                        return nil
                    }

                    guard contentLength > 0 else {
                        print("UPnPControlPoint::startHttpServer() error - content length -- \(contentLength)")
                        return nil
                    }

                    var data = Data(capacity: contentLength)
                    guard try request.remoteSocket?.read(into: &data) == contentLength else {
                        print("UPnPControlPoint::startHttpServer() error - socket read() -- failed")
                        return nil
                    }

                    guard let xmlString = String(data: data, encoding: .utf8) else {
                        print("UPnPControlPoint::startHttpServer() error - xml string failed")
                        return nil
                    }

                    guard let properties = UPnPEventProperties.read(xmlString: xmlString) else {
                        print("UPnPControlPoint::startHttpServer() error - not event properties")
                        return nil
                    }
                    
                    if let sid = request.header["SID"] {
                        print("UPnPControlPoint::startHttpServer() error - sid -- \(sid)")
                        self.eventPropertyListener?(sid, properties)
                    } else {
                        if let sid = request.header["Sid"] {
                            print("UPnPControlPoint::startHttpServer() error - sid -- \(sid)")
                            self.eventPropertyListener?(sid, properties)
                        } else {
                            print("UPnPControlPoint::startHttpServer() error - no sid")
                            return nil
                        }
                    }
                    
                    return HttpResponse(code: 200)
                }
                try self.httpServer!.run()
            } catch let error{
                print("UPnPControlPoint::startHttpServer() error - error - \(error)")
            }
            self.httpServer = nil
        }
    }

And finally, the HTTP server does not properly recognise the header in the request from the device. The method readHeaderString looks for the "\r\n\r\n" as a suffix, while in fact, this delimiter could be found in the middle of the received data.

    func readHeaderString(remoteSocket: Socket?) throws -> String {
        var data = Data(capacity: 1)
        var headerString = ""
        while self.finishing == false {
            if try remoteSocket?.isReadableOrWritable(timeout: 1_000).0 == false {
                continue
            }

            let bytesRead = try remoteSocket?.read(into: &data)
            if bytesRead! <= 0 {
                throw HttpHeaderError.insufficentHeaderString
            }
            headerString += String(data: data, encoding: .utf8)!
            if headerString.hasSuffix("\r\n\r\n") {
                break
            }
        }
        return headerString
    }

Example of headerString after the first pass of the "while loop", where the header delimiter is in the middle of the bytes read.

"NOTIFY /Event/5C8A87D188AA4E6A97BA459FE6190AD2 HTTP/1.1\r\nNt: upnp:event\r\nNts: upnp:propchange\r\nSid: uuid:b3abedf7-ec1f-4c3a-8410-36b062f51772\r\nContent-type: text/xml\r\nSeq: 0\r\nContent-Length: 274\r\nHost: 192.168.30.101:52808\r\nConnection: Keep-Alive\r\nUser-Agent: Linux/3.10.105 UPnP/1.0 BubbleUPnPServer/0.9-update41**\r\n\r\n**<?xml version=\"1.0\" encoding=\"utf-8\" standalone=\"yes\"?><e:propertyset xmlns:e=\"urn:schemas-upnp-org:event-1-0\"><e:property><Duration>290</Duration></e:property><e:property><Seconds>290</Seconds></e:property><e:property><TrackCount>0</TrackCount></e:property></e:propertyset>"

**Comment by meisbedi** [comment]
I finally got it to work. But it is a little bit more involved. The main problem lies with the HTTP server and the handling of the requests. I also suspect an issue with HTTP server and thread safety. I will put the details on the issue of the HTTP server package.

**Comment by meisbedi** [comment]
I solved the problems with changes of the Http Server and the attached files.
Corrected spelling mistakes in UPnPEventSub
Included additional option for lowercase "Sid" in UPnPEventSub
Added the possibility for multiple event listeners in UPnPControlPoint
changed spelling of "listener" in UPnPControlPoint
Adapted the function startHttpServer to the changes in HttpServer

[UPnPControlPoint.swift.zip](https://github.com/bjtj/swift-upnp-tools/files/7595625/UPnPControlPoint.swift.zip)

[UPnPEventSub.swift.zip](https://github.com/bjtj/swift-upnp-tools/files/7595627/UPnPEventSub.swift.zip)

**Comment by bjtj** [comment]
Please try the tag 0.1.15

Thank you!

**Comment by meisbedi** [comment]
I reviewed the code of tag 0.1.15 and it addresses the described issue.
