### ISSUE TITLE
Improvement proposal

### ISSUE THREAD

**Issue by meisbedi** [bjtj/swift-upnp-tools#7]
Meanwhile I extended the control point with additional functions:
Unsubsribe from events, when the app is sent to the background.
Resubscribe, when the app is coming back from the background.
I also think, that the events should not be send to all listeners, but a listener should only receive the events, that match their sid.

examples from my current code in UPnPControlPoint:

    
    public func suspend() {
        for subscriber in self.eventSubscribers {
            subscriber.unsubscribe()
            NSLog("unsubscribed from \(subscriber.service.serviceType ?? "unknown serviceType")")
        }
        self.finish()
    }
    
    public func resume() {
        do {
            try self.run()
        } catch {}
        for subscriber in self.eventSubscribers {
            guard let sid = subscriber.sid, let listener = self.eventPropertyListeners[sid] else { continue }
            subscriber.subscribe(completeListener: { newSubscription in
                NSLog("subscribed to \(newSubscription.service?.serviceType ?? "unknown serviceType")")
                subscriber.sid = newSubscription.sid
                subscriber.callbackUrls = newSubscription.callbackUrls
                if subscriber.sid != sid, newSubscription.sid != "" {
                    self.eventPropertyListeners[sid] = nil
                    self.eventPropertyListeners[newSubscription.sid] = listener
                }
            })
        }
    }

        guard let eventPropertyListener = self.eventPropertyListeners[sid] as? ((String, UPnPEventProperties) -> Void) else {
 //           print("UPnPControlPoint::startHttpServer() error - no listener vor sid \(request.header["User-Agent"])")
            return
        }

        eventPropertyListener(sid, properties)

    
    public func addEventPropertyListener(forSid: String?, listener: ((String, UPnPEventProperties) -> Void)?) {

        guard let sid = forSid else { return }
        let _ = listenerBlock.wait(timeout: .distantFuture)
        if let newListener = listener { self.eventPropertyListeners[sid] = newListener }
        listenerBlock.signal()
        
    }   // of func addEventPropertyListener
    
    public func removeEventPropertyListener(forSid: String?) {
        guard let sid = forSid else { return }
        let _ = listenerBlock.wait(timeout: .distantFuture)
        self.eventPropertyListeners.removeValue(forKey: sid)
        listenerBlock.signal()
    }   // of func addEventPropertyListener

I really appreciate your quick reactions on my findings.

**Comment by bjtj** [comment]
I fixed it

tag: [0.1.16](https://github.com/bjtj/swift-upnp-tools/releases/tag/0.1.16)
- added: suspend & resume in control point
- added: notification handler in event subscriber

Thank you!

**Comment by bjtj** [comment]
Plus, you can get an event subscriber by one of getEventSubscriber* functions

- https://github.com/bjtj/swift-upnp-tools/wiki/UPnPControlPoint#geteventsubscribersid
- https://github.com/bjtj/swift-upnp-tools/wiki/UPnPControlPoint#geteventsubscribersforudn
- https://github.com/bjtj/swift-upnp-tools/wiki/UPnPControlPoint#geteventsubscribersforudnforserviceid
- https://github.com/bjtj/swift-upnp-tools/wiki/UPnPControlPoint#geteventsubscribersforserviceid

Or you can get an event subscriber from subscribe completion handler

- https://github.com/bjtj/swift-upnp-tools/wiki/eventSubscribeCompleteHandler

**Comment by meisbedi** [comment]
Adapted to the lastest version and everything works fine. Unfortunately there remain problems with the http server.
