### ISSUE TITLE
controlpoint resume function brakes links to existing notification handler

### ISSUE THREAD

**Issue by meisbedi** [bjtj/swift-upnp-tools#8]
The current implementation of the resume function of the control point creates completely new subscriptions. Existing links to notification handles are broken. Also, the existing subscriptions from the suspend functions stay in the subscription array. This will inflate the number of subscriptions after several suspend/resume cycles.
Proposal:
Re-use the existing subscription with callback url and handlers and update only the SID of the subscription based on the result of the subscription function.

**Comment by bjtj** [comment]
I fixed in tag 0.1.21

Thank you!
